#!/usr/bin/env python

import argparse
import pandas as pd
import pathlib
import sys
import tqdm

def parse_clargs():
    parser = argparse.ArgumentParser()
    parser.add_argument('input_dir', type=str, nargs='+', help='Input directory.')
    parser.add_argument('output_file', type=str, help='Output file.')

    return (parser.parse_args())

def main():
    clargs = parse_clargs()
    input_files = sum(
        [
            sorted(pathlib.Path(input_dir).glob('**/picks-*.csv'))
            for input_dir in clargs.input_dir
        ],
        []
    )

    picks = list()
    for input_file in tqdm.tqdm(sorted(input_files)):
        picks.append(pd.read_csv(input_file))

    picks = pd.concat(picks, ignore_index=True)

    for time_field in ('start_time', 'end_time', 'peak_time'):
        picks[time_field] = pd.to_datetime(picks[time_field])


    picks = picks.rename(columns=dict(
        start_time='event_start_time',
        end_time='event_end_time',
        peak_time='arrival_time',
        peak_value='probability'
    ))
    picks = picks.sort_values(['network', 'station', 'event_start_time'])

    picks.to_hdf(clargs.output_file, key='picks', format='table')

if __name__ == '__main__':
    main()
